// Should be auto-generated by python script based on cap bank esr at different
// frequencies and booster
// efficiency curves
#ifndef _VSAFE_H_
#define _VSAFE_H_

#if CONFIG == 0
// Min voltage 1.8
/*#define VSAFE_ID10 2556
#define VSAFE_ID11 2651
#define VSAFE_ID12 2794
#define VSAFE_ID1 3496
#define VSAFE_ID3 2885
#define VSAFE_ID4 3302
#define VSAFE_ID6 2594
#define VSAFE_ID7 2732
#define VSAFE_ID8 3011
#define VSAFE_ID9 3441
*/
/* More aggressive with eff from 3.3V table
#define VSAFE_ID10 2422
#define VSAFE_ID11 2515
#define VSAFE_ID12 2661
#define VSAFE_ID1 2924
#define VSAFE_ID1 2894
#define VSAFE_ID3 2625
#define VSAFE_ID4 2944
#define VSAFE_ID6 2453
#define VSAFE_ID7 2581
#define VSAFE_ID8 2803
#define VSAFE_ID9 3260
*/
/*
#define VSAFE_ID10 2472
#define VSAFE_ID11 2613
#define VSAFE_ID12 2836
#define VSAFE_ID1 3216
#define VSAFE_ID3 2784
#define VSAFE_ID4 3279
#define VSAFE_ID6 2518
#define VSAFE_ID7 2716
#define VSAFE_ID8 3054
#define VSAFE_ID9 3369

#define VSAFE_ID13 1000 
#define VSAFE_ID14 1000 
#define VSAFE_ID15 1000 
#define VSAFE_ID16 1000 
#define VSAFE_ID17 1000 
#define VSAFE_ID18 1000 
#define VSAFE_ID19 1000 
#define VSAFE_ID20 1000 
#define VSAFE_ID21 1000 
#define VSAFE_ID22 1000 

#define VSAFE_ID23 1000 
#define VSAFE_ID24 1000 
#define VSAFE_ID25 1000 
#define VSAFE_ID26 1000 
#define VSAFE_ID27 1000 
#define VSAFE_ID28 1000 
#define VSAFE_ID29 1000 
#define VSAFE_ID30 1000 
#define VSAFE_ID31 1000 
#define VSAFE_ID32 1000 
#define VSAFE_ID33 1000 
#define VSAFE_ID34 1000 
#define VSAFE_ID35 1000 
#define VSAFE_ID36 1000 
*/
#define VSAFE_ID13 3207
#define VSAFE_ID14 3666
#define VSAFE_ID15 2819
#define VSAFE_ID16 3225
#define VSAFE_ID17 3728
#define VSAFE_ID18 2518
#define VSAFE_ID19 2710
#define VSAFE_ID20 3069
#define VSAFE_ID21 3512
#define VSAFE_ID22 2474
#define VSAFE_ID23 2604
#define VSAFE_ID24 2786
#define VSAFE_ID25 3197
#define VSAFE_ID26 3666
#define VSAFE_ID27 2795
#define VSAFE_ID28 3298
#define VSAFE_ID29 4128
#define VSAFE_ID30 2510
#define VSAFE_ID31 2657
#define VSAFE_ID32 3006
#define VSAFE_ID33 3518
#define VSAFE_ID34 2463
#define VSAFE_ID35 2593
#define VSAFE_ID36 2779
#define VSAFE_ID10 2472
#define VSAFE_ID11 2613
#define VSAFE_ID12 2836
#define VSAFE_ID1 3289
#define VSAFE_ID1 3216
#define VSAFE_ID3 2784
#define VSAFE_ID4 3279
#define VSAFE_ID6 2518
#define VSAFE_ID7 2716
#define VSAFE_ID8 3054
#define VSAFE_ID9 3369

#elif CONFIG == 1
// Min voltage 1.6

#include "vsafe_1.6_0.045"

#include "culpeo_APDS_1.6"
#include "culpeo_BLE_1.6"
#include "culpeo_ML_1.6"

#else

#error "No vsafes defined for config"

#endif
#endif

