// Should be auto-generated by python script based on cap bank esr at different
// frequencies and booster
// efficiency curves
#ifndef _VSAFE_H_
#define _VSAFE_H_

#if CONFIG == 0
// Min voltage 1.8
/*#define VSAFE_ID10 2556
#define VSAFE_ID11 2651
#define VSAFE_ID12 2794
#define VSAFE_ID1 3496
#define VSAFE_ID3 2885
#define VSAFE_ID4 3302
#define VSAFE_ID6 2594
#define VSAFE_ID7 2732
#define VSAFE_ID8 3011
#define VSAFE_ID9 3441
*/
/* More aggressive with eff from 3.3V table
#define VSAFE_ID10 2422
#define VSAFE_ID11 2515
#define VSAFE_ID12 2661
#define VSAFE_ID1 2924
#define VSAFE_ID1 2894
#define VSAFE_ID3 2625
#define VSAFE_ID4 2944
#define VSAFE_ID6 2453
#define VSAFE_ID7 2581
#define VSAFE_ID8 2803
#define VSAFE_ID9 3260
*/
/*
#define VSAFE_ID10 2472
#define VSAFE_ID11 2613
#define VSAFE_ID12 2836
#define VSAFE_ID1 3216
#define VSAFE_ID3 2784
#define VSAFE_ID4 3279
#define VSAFE_ID6 2518
#define VSAFE_ID7 2716
#define VSAFE_ID8 3054
#define VSAFE_ID9 3369

#define VSAFE_ID13 1000 
#define VSAFE_ID14 1000 
#define VSAFE_ID15 1000 
#define VSAFE_ID16 1000 
#define VSAFE_ID17 1000 
#define VSAFE_ID18 1000 
#define VSAFE_ID19 1000 
#define VSAFE_ID20 1000 
#define VSAFE_ID21 1000 
#define VSAFE_ID22 1000 

#define VSAFE_ID23 1000 
#define VSAFE_ID24 1000 
#define VSAFE_ID25 1000 
#define VSAFE_ID26 1000 
#define VSAFE_ID27 1000 
#define VSAFE_ID28 1000 
#define VSAFE_ID29 1000 
#define VSAFE_ID30 1000 
#define VSAFE_ID31 1000 
#define VSAFE_ID32 1000 
#define VSAFE_ID33 1000 
#define VSAFE_ID34 1000 
#define VSAFE_ID35 1000 
#define VSAFE_ID36 1000 
*/
#define VSAFE_ID13 3207
#define VSAFE_ID14 3666
#define VSAFE_ID15 2819
#define VSAFE_ID16 3225
#define VSAFE_ID17 3728
#define VSAFE_ID18 2518
#define VSAFE_ID19 2710
#define VSAFE_ID20 3069
#define VSAFE_ID21 3512
#define VSAFE_ID22 2474
#define VSAFE_ID23 2604
#define VSAFE_ID24 2786
#define VSAFE_ID25 3197
#define VSAFE_ID26 3666
#define VSAFE_ID27 2795
#define VSAFE_ID28 3298
#define VSAFE_ID29 4128
#define VSAFE_ID30 2510
#define VSAFE_ID31 2657
#define VSAFE_ID32 3006
#define VSAFE_ID33 3518
#define VSAFE_ID34 2463
#define VSAFE_ID35 2593
#define VSAFE_ID36 2779
#define VSAFE_ID10 2472
#define VSAFE_ID11 2613
#define VSAFE_ID12 2836
#define VSAFE_ID1 3289
#define VSAFE_ID1 3216
#define VSAFE_ID3 2784
#define VSAFE_ID4 3279
#define VSAFE_ID6 2518
#define VSAFE_ID7 2716
#define VSAFE_ID8 3054
#define VSAFE_ID9 3369

#elif CONFIG == 1
// Min voltage 1.6
#define VSAFE_ID13 3047
#define VSAFE_ID14 3524
#define VSAFE_ID15 2547
#define VSAFE_ID16 3073
#define VSAFE_ID17 3580
#define VSAFE_ID18 2283
#define VSAFE_ID19 2498
#define VSAFE_ID20 2901
#define VSAFE_ID21 3399
#define VSAFE_ID22 2234
#define VSAFE_ID23 2379
#define VSAFE_ID24 2585
#define VSAFE_ID25 3035
#define VSAFE_ID26 3949
#define VSAFE_ID27 2594
#define VSAFE_ID28 3156
#define VSAFE_ID29 3867
#define VSAFE_ID30 2274
#define VSAFE_ID31 2440
#define VSAFE_ID32 2831
#define VSAFE_ID33 3406
#define VSAFE_ID34 2222
#define VSAFE_ID35 2367
#define VSAFE_ID36 2577
#define VSAFE_ID10 2224
#define VSAFE_ID11 2390
#define VSAFE_ID12 2641
#define VSAFE_ID1 3127
#define VSAFE_ID1 3056
#define VSAFE_ID3 2581
#define VSAFE_ID4 3134
#define VSAFE_ID6 2283
#define VSAFE_ID7 2505
#define VSAFE_ID8 2885
#define VSAFE_ID9 3239

#define VSAFE_ID_APDS 2725
#define VSAFE_ID_BLE 3038
#define VSAFE_ID_ML 2988

// Less aggressive, nominal cap
/*#define VSAFE_ID10 2224
#define VSAFE_ID11 2390
#define VSAFE_ID12 2641
#define VSAFE_ID1 3127
#define VSAFE_ID1 3056
#define VSAFE_ID3 2581
#define VSAFE_ID4 3134
#define VSAFE_ID6 2283
#define VSAFE_ID7 2505
#define VSAFE_ID8 2885
#define VSAFE_ID9 3239
*/
/*
#define VSAFE_ID10 2295
#define VSAFE_ID11 2383
#define VSAFE_ID12 2526
#define VSAFE_ID1 3274
#define VSAFE_ID3 2629
#define VSAFE_ID4 3053
#define VSAFE_ID6 2327
#define VSAFE_ID7 2466
#define VSAFE_ID8 2747
#define VSAFE_ID9 3178
*/
/*
#define VSAFE_ID10 2224
#define VSAFE_ID11 2390
#define VSAFE_ID12 2641
//#define VSAFE_ID1 3056
// More aggressive swap in
#define VSAFE_ID1 3004
#define VSAFE_ID3 2581
#define VSAFE_ID4 3134
#define VSAFE_ID6 2283
#define VSAFE_ID7 2505
#define VSAFE_ID8 2885
//#define VSAFE_ID9 3239
#define VSAFE_ID9 3230
*/

/*More aggressive set*/
// Measured capacitance, 
/*#define VSAFE_ID10 2221
#define VSAFE_ID11 2388
#define VSAFE_ID12 2639
#define VSAFE_ID1 3004
#define VSAFE_ID3 2567
#define VSAFE_ID4 3112
#define VSAFE_ID6 2280
#define VSAFE_ID7 2501
#define VSAFE_ID8 2879
#define VSAFE_ID9 3230
*/
/* Even more aggressive*/
/*#define VSAFE_ID10 2177
#define VSAFE_ID11 2282
#define VSAFE_ID12 2447
#define VSAFE_ID1 2741
#define VSAFE_ID3 2413
#define VSAFE_ID4 2777
#define VSAFE_ID6 2213
#define VSAFE_ID7 2357
#define VSAFE_ID8 2608
#define VSAFE_ID9 3123
*/
#elif CONFIG == 2
// Min voltage 1.0
/*
#define VSAFE_ID10 1547
#define VSAFE_ID11 1584
#define VSAFE_ID12 1727
#define VSAFE_ID1 2664
#define VSAFE_ID3 1888
#define VSAFE_ID4 2339
#define VSAFE_ID6 1567
#define VSAFE_ID7 1678
#define VSAFE_ID8 1965
#define VSAFE_ID9 2400
*/
/* chill version, with 1.8V output eff.
#define VSAFE_ID10 1457
#define VSAFE_ID11 1551
#define VSAFE_ID12 1692
#define VSAFE_ID1 2268
#define VSAFE_ID1 2058
#define VSAFE_ID3 1711
#define VSAFE_ID4 2059
#define VSAFE_ID6 1489
#define VSAFE_ID7 1619
#define VSAFE_ID8 1883
#define VSAFE_ID9 2294
*/
// 1.8V output eff and 45mF cap
/*#define VSAFE_ID10 1541
#define VSAFE_ID11 1806
#define VSAFE_ID12 1977
#define VSAFE_ID1 2411
#define VSAFE_ID3 2096
#define VSAFE_ID4 3053
#define VSAFE_ID6 1635
#define VSAFE_ID7 1829
#define VSAFE_ID8 2590
#define VSAFE_ID9 3833
*/
//1.2 lo
#define VSAFE_ID10 1758
#define VSAFE_ID11 1980
#define VSAFE_ID12 2123
#define VSAFE_ID1 2876
#define VSAFE_ID1 2829
#define VSAFE_ID3 2227
#define VSAFE_ID4 2952
#define VSAFE_ID6 1837
#define VSAFE_ID7 2132
#define VSAFE_ID8 2636
#define VSAFE_ID9 3103

/* less aggressive, with 1.8V output eff.
#define VSAFE_ID10 1457
#define VSAFE_ID11 1551
#define VSAFE_ID12 1692
#define VSAFE_ID1 2268
#define VSAFE_ID1 2058
#define VSAFE_ID3 1711
#define VSAFE_ID4 2059
#define VSAFE_ID6 1489
#define VSAFE_ID7 1619
#define VSAFE_ID8 1883
#define VSAFE_ID9 2294

// more aggressive with 3.3V output eff
#define VSAFE_ID10 1509
#define VSAFE_ID11 1734
#define VSAFE_ID12 1862
#define VSAFE_ID1 2600
#define VSAFE_ID1 2269
#define VSAFE_ID3 2010
#define VSAFE_ID4 2822
#define VSAFE_ID6 1601
#define VSAFE_ID7 1760
#define VSAFE_ID8 2407
#define VSAFE_ID9 3406
*/

#define VSAFE_ID13 1000 
#define VSAFE_ID14 1000 
#define VSAFE_ID15 1000 
#define VSAFE_ID16 1000 
#define VSAFE_ID17 1000 
#define VSAFE_ID18 1000 
#define VSAFE_ID19 1000 
#define VSAFE_ID20 1000 
#define VSAFE_ID21 1000 
#define VSAFE_ID22 1000 

#define VSAFE_ID23 1000 
#define VSAFE_ID24 1000 
#define VSAFE_ID25 1000 
#define VSAFE_ID26 1000 
#define VSAFE_ID27 1000 
#define VSAFE_ID28 1000 
#define VSAFE_ID29 1000 
#define VSAFE_ID30 1000 
#define VSAFE_ID31 1000 
#define VSAFE_ID32 1000 
#define VSAFE_ID33 1000 
#define VSAFE_ID34 1000 
#define VSAFE_ID35 1000 
#define VSAFE_ID36 1000 

#else

#error "No vsafes defined for config"

#endif
#endif

