
plot_synthetic:
	python3 plot_synthetic_loads_redux.py

plot_mezzos:
	python3 plot_mezzo_expts.py catnap_multi_vsafes_1.6.pkl culpeo_multi_vsafes_1.6.pkl conservative_multi_vsafes_1.6.pkl datasheet_multi_vsafes_1.6.pkl


plot_9way:
	python3 plot_9way.py results/case_study/apds_30s_clean_charge-to-full.csv results/case_study/apds_30s_clean_catnap.csv results/case_study/apds_60s_clean_culpeo.csv results/case_study/culpeo_vsafe_charge_up.csv results/case_study/catnap_vsafe_charge_up.csv
