// Should be auto-generated by python script based on cap bank esr at different
// frequencies and booster
// efficiency curves
#ifndef _VSAFE_H_
#define _VSAFE_H_

#if CONFIG == 0

#error "No settings for 0!"

#elif CONFIG == 1
// Min voltage 1.6

#include "vsafe_1.6_0.045"

/*#include "meas_vcap_APDS_1.6"
#include "meas_vcap_BLE_1.6"
#include "meas_vcap_ML_1.6"*/

#else

#error "No vsafes defined for config"

#endif
#endif

