// Should be auto-generated by python script based on cap bank esr at different
// frequencies and booster
// efficiency curves
#ifndef _VSAFE_H_
#define _VSAFE_H_

#if CONFIG == 0
// Min voltage 1.8
#define VSAFE_ID10 2556
#define VSAFE_ID11 2651
#define VSAFE_ID12 2794
#define VSAFE_ID1 3496
#define VSAFE_ID3 2885
#define VSAFE_ID4 3302
#define VSAFE_ID6 2594
#define VSAFE_ID7 2732
#define VSAFE_ID8 3011
#define VSAFE_ID9 3441

#elif CONFIG == 1
// Min voltage 1.6
/*
#define VSAFE_ID10 2295
#define VSAFE_ID11 2383
#define VSAFE_ID12 2526
#define VSAFE_ID1 3274
#define VSAFE_ID3 2629
#define VSAFE_ID4 3053
#define VSAFE_ID6 2327
#define VSAFE_ID7 2466
#define VSAFE_ID8 2747
#define VSAFE_ID9 3178
*/
#define VSAFE_ID10 2294
#define VSAFE_ID11 2407
#define VSAFE_ID12 2577
#define VSAFE_ID1 3098
#define VSAFE_ID3 2616
#define VSAFE_ID4 3052
#define VSAFE_ID6 2334
#define VSAFE_ID7 2492
#define VSAFE_ID8 2812
#define VSAFE_ID9 3310

#elif CONFIG == 2
// Min voltage 1.0
/*
#define VSAFE_ID10 1547
#define VSAFE_ID11 1584
#define VSAFE_ID12 1727
#define VSAFE_ID1 2664
#define VSAFE_ID3 1888
#define VSAFE_ID4 2339
#define VSAFE_ID6 1567
#define VSAFE_ID7 1678
#define VSAFE_ID8 1965
#define VSAFE_ID9 2400
*/
#define VSAFE_ID10 1457
#define VSAFE_ID11 1551
#define VSAFE_ID12 1692
#define VSAFE_ID1 2268
#define VSAFE_ID1 2058
#define VSAFE_ID3 1711
#define VSAFE_ID4 2059
#define VSAFE_ID6 1489
#define VSAFE_ID7 1619
#define VSAFE_ID8 1883
#define VSAFE_ID9 2294
#else

#error "No vsafes defined for config"

#endif
#endif

